x-ci-base: &ci-base
  build:
    context: .
    dockerfile: Dockerfile.ci
  read_only: true
  tmpfs:
    - /tmp:exec,mode=1777

x-ci-env: &ci-env
  COMPOSER_HOME: /home/ci/.composer
  CI_WORK_BASE: /tmp

services:
  ci-dev:
    <<: *ci-base
    volumes:
      - ".:/src:ro"
      - "composer_home_dev:/home/ci/.composer"
      - "npm_cache_dev:/home/ci/.npm"
    environment:
      <<: *ci-env
      APP_PIPELINE: dev
    command: bash /src/bin/ci

  ci-preview:
    <<: *ci-base
    volumes:
      - ".:/src:ro"
      - "composer_home_preview:/home/ci/.composer"
      - "npm_cache_preview:/home/ci/.npm"
    environment:
      <<: *ci-env
      APP_PIPELINE: preview
    command: bash /src/bin/ci

volumes:
  composer_home_dev:
  npm_cache_dev:
  composer_home_preview:
  npm_cache_preview:
