name: Admin

on:
  workflow_dispatch:
    inputs:
      command:
        description: 'Admin-Befehl'
        required: true
        type: choice
        options:
          - reset-preview

jobs:
  run:
    if: inputs.command == 'reset-preview'
    uses: ./.github/workflows/preview-cd.yml
    with:
      last-deploy-commit: ""
    secrets: inherit
